project_id = "mfjfhnwgrbwjovvnlxto"

[functions.get-data]
verify_jwt = false

[functions.create-booking]
verify_jwt = true

[functions.get-user-data]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.auth-email]
verify_jwt = false

[functions.send-notification]
verify_jwt = true