-- Insert Terms of Service into site_settings
INSERT INTO public.site_settings (key, value, description) VALUES 
('terms_of_service', '{
  "title": "Regulamin świadczenia usług",
  "content": "§ 1 POSTANOWIENIA OGÓLNE\n\n1. Niniejszy Regulamin określa zasady świadczenia usług spa i wellness.\n2. Usługodawcą jest [Nazwa firmy] z siedzibą w [Adres].\n3. Korzystanie z usług oznacza akceptację niniejszego Regulaminu.\n\n§ 2 REZERWACJE\n\n1. Rezerwacji można dokonać telefonicznie, osobiście lub przez stronę internetową.\n2. Rezerwacja wymaga podania imienia, nazwiska i numeru telefonu.\n3. Potwierdzenie rezerwacji następuje w momencie otrzymania odpowiedzi zwrotnej.\n\n§ 3 ODWOŁANIA I ZMIANY\n\n1. Odwołanie wizyty jest możliwe do 24 godzin przed planowanym terminem.\n2. W przypadku późniejszego odwołania pobierana jest opłata w wysokości 50% wartości zabiegu.\n3. Niestawienie się na wizytę skutkuje pobraniem pełnej opłaty.\n\n§ 4 PŁATNOŚCI\n\n1. Płatność za usługi następuje po zakończeniu zabiegu.\n2. Akceptujemy płatności gotówką i kartą.\n3. Faktury VAT wystawiamy na życzenie Klienta.\n\n§ 5 ZASADY KORZYSTANIA Z USŁUG\n\n1. Klient zobowiązany jest do przybycia punktualnie na umówioną wizytę.\n2. Spóźnienie może skutkować skróceniem czasu zabiegu.\n3. Przed zabiegiem należy poinformować o przeciwwskazaniach zdrowotnych.\n4. Zabrania się korzystania z usług pod wpływem alkoholu lub środków odurzających.\n\n§ 6 ODPOWIEDZIALNOŚĆ\n\n1. Salon nie ponosi odpowiedzialności za pozostawione przedmioty osobiste.\n2. Klient ponosi odpowiedzialność za szkody spowodowane umyślnie.\n3. W przypadku przeciwwskazań zdrowotnych salon zastrzega sobie prawo do odmowy świadczenia usługi.\n\n§ 7 DANE OSOBOWE\n\n1. Dane osobowe są przetwarzane zgodnie z Polityką Prywatności.\n2. Klient wyraża zgodę na przetwarzanie danych w celu świadczenia usług.\n\n§ 8 POSTANOWIENIA KOŃCOWE\n\n1. Regulamin wchodzi w życie z dniem [data].\n2. Salon zastrzega sobie prawo do zmiany Regulaminu.\n3. W sprawach spornych właściwy jest sąd miejsca siedziby salonu."
}', 'Regulamin świadczenia usług spa i wellness');

-- Insert Privacy Policy into site_settings  
INSERT INTO public.site_settings (key, value, description) VALUES
('privacy_policy', '{
  "title": "Polityka Prywatności",
  "content": "INFORMACJA O PRZETWARZANIU DANYCH OSOBOWYCH\n\n§ 1 ADMINISTRATOR DANYCH\n\n1. Administratorem Państwa danych osobowych jest [Nazwa firmy] z siedzibą w [Adres].\n2. Kontakt z administratorem: [email], [telefon].\n3. Inspektor ochrony danych: [kontakt] (jeśli wymagany).\n\n§ 2 PODSTAWA PRAWNA PRZETWARZANIA\n\n1. Dane przetwarzamy na podstawie:\n   - wykonania umowy (art. 6 ust. 1 lit. b RODO)\n   - prawnie uzasadnionego interesu (art. 6 ust. 1 lit. f RODO)\n   - zgody (art. 6 ust. 1 lit. a RODO)\n\n§ 3 CELE PRZETWARZANIA DANYCH\n\n1. Świadczenie usług spa i wellness\n2. Obsługa rezerwacji i płatności\n3. Kontakt z klientami\n4. Marketing (za zgodą)\n5. Prowadzenie dokumentacji medycznej\n6. Wystawienie faktur\n\n§ 4 KATEGORIE DANYCH\n\n1. Dane identyfikacyjne (imię, nazwisko)\n2. Dane kontaktowe (telefon, email, adres)\n3. Dane o stanie zdrowia (w zakresie niezbędnym do świadczenia usług)\n4. Dane o preferencjach i historii wizyt\n\n§ 5 OKRES PRZECHOWYWANIA\n\n1. Dane do realizacji umowy - przez okres świadczenia usług\n2. Dane księgowe - 5 lat\n3. Dokumentacja medyczna - zgodnie z przepisami prawa\n4. Marketing - do cofnięcia zgody\n\n§ 6 ODBIORCY DANYCH\n\n1. Podmioty przetwarzające dane w naszym imieniu:\n   - dostawcy systemów IT\n   - firmy księgowe\n   - dostawcy usług płatniczych\n2. Organy publiczne (na podstawie przepisów prawa)\n\n§ 7 PRAWA OSOBY, KTÓREJ DANE DOTYCZĄ\n\n1. Prawo dostępu do danych\n2. Prawo do sprostowania danych\n3. Prawo do usunięcia danych\n4. Prawo do ograniczenia przetwarzania\n5. Prawo do przenoszenia danych\n6. Prawo sprzeciwu\n7. Prawo do cofnięcia zgody\n\n§ 8 BEZPIECZEŃSTWO DANYCH\n\n1. Stosujemy odpowiednie środki techniczne i organizacyjne\n2. Dane są chronione przed nieuprawnionym dostępem\n3. Regularne kopie zapasowe\n4. Szkolenia personelu w zakresie ochrony danych\n\n§ 9 PLIKI COOKIES\n\n1. Strona internetowa wykorzystuje pliki cookies\n2. Cookies służą poprawie funkcjonalności strony\n3. Można zarządzać cookies w ustawieniach przeglądarki\n\n§ 10 ZMIANY POLITYKI\n\n1. Zastrzegamy sobie prawo do aktualizacji Polityki\n2. O zmianach informujemy na stronie internetowej\n3. Istotne zmiany komunikujemy bezpośrednio\n\n§ 11 SKARGI\n\n1. Prawo do złożenia skargi do Prezesa UODO\n2. Kontakt: ul. Stawki 2, 00-193 Warszawa\n\nDane kontaktowe do spraw ochrony danych: [email]"
}', 'Polityka prywatności i ochrony danych osobowych');