// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfjfhnwgrbwjovvnlxto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mamZobndncmJ3am92dm5seHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTIwMTQsImV4cCI6MjA2ODc4ODAxNH0.J6hOEg8PYNhdxsUmhwl0UcJXEveun4o7Wzq0jnGtrd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});